name: Deploy to EC2

on:
  push:
    branches:
      - main # This can be the branch you want to trigger deployment on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP_ADDRESS }} << 'EOF'
            cd /path/to/your/project
            git pull origin main  # Or any other command to pull and deploy your code
            npm install           # Or other commands to build and run your app
            pm2 restart app       # Or however you manage your app (e.g., using pm2)
          EOF
